routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Route::get('/', function () {
//     return redirect()->intended('/login');
// });

// Route::get('{any}', 'UboldController@index');
Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

Route::group(["prefix" => "admin", "namespace" => "Admin",'middleware' => 'auth'], function () {

    /********************************Role */

    Route::resource('role','RoleController');
    Route::post('role/update', 'RoleController@update')->name('role.update');
    Route::get('role/destroy/{id}', 'RoleController@destroy');
    Route::get('/search-permission', 'RoleController@searchPermission')->name('search.permission');

    /********************************Permission */

    Route::resource('permission','PermissionController');
    Route::post('permission/update', 'PermissionController@update')->name('permission.update');
    Route::get('permission/destroy/{id}', 'PermissionController@destroy');

    /********************************User */

    Route::resource('user','UserController');
    Route::post('user/update', 'UserController@update')->name('user.update');
    Route::get('user/destroy/{id}', 'UserController@destroy');
    Route::get('/search-role', 'UserController@searchRole')->name('search.role');

    /******************************Zone */

    Route::resource('zone','ZoneController');
    Route::post('zone/update', 'ZoneController@update')->name('zone.update');
    Route::get('zone/destroy/{id}', 'ZoneController@destroy');
    Route::get('/search-country/{keyword?}', 'ZoneController@searchCountry')->name('search.country');
    Route::get('/search-state/{keyword?}', 'ZoneController@searchState')->name('search.state');
    Route::get('/search-city/{keyword?}', 'ZoneController@searchCity')->name('search.city');

    /******************************Channel Patner */

    Route::resource('channelpartner','ChannelPartnerController');
    Route::post('channelpartner/update', 'ChannelPartnerController@update')->name('channelpartner.update');
    Route::get('channelpartner/destroy/{id}', 'ChannelPartnerController@destroy');
    Route::get('/search-channelpartnertype', 'ChannelPartnerController@searchChannelPartnerType')->name('search.channelpartnertype');

    Route::resource('channelpartnertype','ChannelPartnerTypeController');
    Route::post('channelpartnertype/update', 'ChannelPartnerTypeController@update')->name('channelpartnertype.update');
    Route::get('channelpartnertype/destroy/{id}', 'ChannelPartnerTypeController@destroy');

    Route::resource('product','ProductController');
    Route::post('product/update', 'ProductController@update')->name('product.update');
    Route::get('product/destroy/{id}', 'ProductController@destroy');
    

    Route::resource('subproduct','SubProductController');
    Route::post('subproduct/update', 'SubProductController@update')->name('subproduct.update');
    Route::get('subproduct/destroy/{id}', 'SubProductController@destroy');
    Route::get('/search-product/{keyword?}', 'SubProductController@searchProduct')->name('search.product');

    Route::resource('subsubproduct','SubSubProductController');
    Route::post('subsubproduct/update', 'SubSubProductController@update')->name('subsubproduct.update');
    Route::get('subsubproduct/destroy/{id}', 'SubSubProductController@destroy');
    Route::get('/search-subproduct/{keyword?}', 'SubSubProductController@searchSubProduct')->name('search.subproduct');
    Route::get('/search-subsubproduct/{keyword?}', 'SubSubProductController@searchSubSubProduct')->name('search.subsubproduct');
    Route::get('/subsubproduct/getdata/{id}','SubSubProductController@getdataSubSubProduct')->name('search.getsubsubproduct');

    Route::post('prospect/{id}/update', 'ProspectController@update')->name('prospect.updateprospect');
    Route::get('prospect/destroy/{id}', 'ProspectController@destroy');
    Route::get('prospect/quickcreate', 'ProspectController@quickcreate')->name('prospect.quickcreate');
    Route::resource('prospect','ProspectController');

    
    Route::get('search-prospectcountry/{keyword?}', 'ProspectController@searchCountry')->name('prospect-country');
    Route::get('search-prospectstate/{keyword?}', 'ProspectController@searchState')->name('prospect-state');
    Route::get('search-prospectcity/{keyword?}', 'ProspectController@searchCity')->name('prospect-city');
    Route::post('prospect/quickstore', 'ProspectController@quickstore')->name('prospect.quickstore');


});

app/Models/Zone.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Zone extends Model
{
    protected $fillable = [
        'zonename', 'country', 'state', 'city'
       ];
}

app/Http/Controllers/Admin/ZoneController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\Zone\DeleteZoneRequest;
use App\Models\City;
use App\Models\Country;
use App\Models\State;
use App\Models\Zone;
use App\Ntrax\Repositories\Zone\ZoneInterface;
use App\Http\Requests\Zone\IndexZoneRequest;
use App\Http\Requests\Zone\StoreZoneRequest;
use App\Http\Requests\Zone\UpdateZoneRequest;
use DataTables;
use Illuminate\Support\Facades\DB;
use Validator;
use Zizaco\Entrust\EntrustFacade as Entrust;

class ZoneController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    private $zone;
    private $country;
    private $state;
    private $city;
    public function __construct(ZoneInterface $zone,Country $country, State $state, City $city)
     {
         $this->zone = $zone;
         $this->country = $country;
         $this->state = $state;
         $this->city = $city;
     }
    public function index(IndexZoneRequest $request)
    {
        if ($request->ajax()) {
         return   $zones = $this->zone->getallzonesdetails($request);
        }
        return view('admin.zone.index');
        

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $country = $this->country->all();
        $states = $this->state->all();
        $citys = $this->city->all();

        return view('admin.zone/create',compact('country','states','city'));
    }

    public function searchCountry($keyword=null)
    {
        $countries = $this->zone->searchCountry($keyword);
        $countryArray=[];
        foreach ($countries as $countrykey=>$country){
            $countryArray[$countrykey]['id']=$country->id;
            $countryArray[$countrykey]['text']=$country->country_name;
        }
        return $countryArray;
    }

    public function searchState($keyword=null,Request $request)
    {
        $states = $this->zone->searchState($keyword,$request);
        $stateArray=[];
        foreach ($states as $stateykey=>$state){
            $stateArray[$stateykey]['id']=$state->id;
            $stateArray[$stateykey]['text']=$state->state_name;
        }
        return $stateArray;
    }

    public function searchCity($keyword=null,Request $request)
    {
        $cities = $this->zone->searchCity($keyword,$request);
        $cityArray=[];
        $cityuu = [];
        foreach ($cities as $citykey=>$citys){
            foreach($citys as $citykeys=> $city){
                $cityArray[$citykey][$citykeys]['id']=$city->id;
                $cityArray[$citykey][$citykeys]['text']=$city->city_name;
            }
            
        }
        return array_merge($cityArray[0],$cityArray[1]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreZoneRequest $request)
    {
        // dd($request->all());
        // $rules = array(
        //     'zonename'    =>  'required',
        //     'country'     =>  'required',
        //     'state'       =>  'required',
        //     'city'        =>'required'
        // );

        // $error = Validator::make($request->all(), $rules);

        // if($error->fails())
        // {
        //     return response()->json(['errors' => $error->errors()->all()]);
        // }
        DB::beginTransaction();
        try{
            DB::commit();
        $savezone = $this->zone->storezone($request);
        return response()->json(['success' => 'Data Added successfully.']);
        }  catch (\Exception $e) {
            DB::rollBack();
            logger($e->getMessage());
            return redirect()->back()->with('error', 'Failed to Add');
        }
       
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(request()->ajax())
        {
            $data = $this->zone->geteditdata($id);
            return response()->json(['data' => $data]);
        }
    }
   
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateZoneRequest $request)
    {
        DB::beginTransaction();
        try{
            $savezone = $this->zone->updatezone($request);
            DB::commit();
            return response()->json(['success' => 'Data is successfully updated.']);
        }  catch (\Exception $e) {
            DB::rollBack();
            logger($e->getMessage());
            return redirect()->back()->with('error', 'Update failed');
        }

        
       
    }

    

    /**
     * Remove the specified resource from storage.$dd =
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(Entrust::can('Delete Zone') ? 'true' : 'false' != 'false')
        {
        $data = $this->zone->destroyzone($id);
        return response()->json(['success'=>'Zone deleted successfully.']);
        } else {
            return response()->json(['errors'=>'You Dont Have Permission to Delete.']);
        }
    }
}

resources/views/admin/zone/create.blade.php
@extends('layouts.master')

@section('content')

                    <!-- Start Content-->
                    <div class="container-fluid">
                        
                        <!-- start page title -->
                        <div class="row">
                            <div class="col-12">
                                <div class="page-title-box">
                                    <div class="page-title-right">
                                        <ol class="breadcrumb m-0">
                                            <li class="breadcrumb-item"><a href="javascript: void(0);">UBold</a></li>
                                            <li class="breadcrumb-item"><a href="javascript: void(0);">Pages</a></li>
                                            <li class="breadcrumb-item active">Starter</li>
                                        </ol>
                                    </div>
                                    <h4 class="page-title">Starter</h4>
                                </div>
                            </div>
                        </div>     
                        <!-- end page title --> 
                        <div class="row">
                            <div class="col-12">
                                <div class="card">
                                    <div class="card-body">
                                    <form action="{{route('zone.store')}}" method="post">
                                        {{csrf_field()}}
                                        <div class="row">
                                            <div class="col-md-3">
                                                <input type="text" class="form-control" name="zonename" id="" placeholder="Enter ZoneName">
                                                <small id="helpId" class="text-muted">Enter Zone Name <span class="red" style="color:red;font-size:12px">*</span></small>
                                            </div>

                                            <div class="col-md-3">
                                                <select class="form-control select2-multiple country-select2" data-toggle="select2" data-placeholder="Choose Country..." name="country_name[]" id="country_name">
                                                </select>
                                            </div>

                                            <div class="col-md-3">
                                                <select class="form-control select2-multiple state-select2" data-toggle="select2" multiple="multiple" data-placeholder="Choose State..." name="state_name[]" id="state_name">
                                                </select>
                                            </div>
                                            <div class="col-md-3">
                                                <select class="form-control select2-multiple city-select2" data-toggle="select2" multiple="multiple" data-placeholder="Choose City..." name="city_name[]" id="city_name">
                                                </select>
                                            </div>
                                           <div class="col-md-3">
                                                <button type="submit" class="btn btn-outline-success btn-rounded waves-effect waves-light">Save</button>
                                           </div>
                                        </div> 
                                    </form>

                                    </div> 
                                </div> 
                            </div> 
                        </div> 
                        
                    </div> <!-- container -->

@endsection
@section('script')
<script>
 $(document).ready(function () {
      $(".country-select2").select2({
        ajax: {
            url: function (params) {
                return "{{route('search.country').'/'}}" + params.term;
            },
            dataType: 'json',
            delay: 250,
            data: function (params) {
                return {q: params.term, };
            },
            processResults: function (data, params) {
                return {results: data};
            },
            cache: true
        },
        minimumInputLength: 3,
    });


    $( ".country-select2" ) .change(function () {
        $("#state_name").val('');
        $("#city_name").val('');
        let param_new = $(this).val();
        var param_country = "?country_id="+param_new;
        $(".state-select2").select2({
        ajax: {
            url: function (param) {
                return "{{route('search.state').'/'}}" + param.term + param_country;
            },
            dataType: 'json',
            delay: 250,
            data: function (param) {
                return {q: param.term, };
            },
            processResults: function (data, param) {
                return {results: data};
            },
            cache: true
        },
        // minimumInputLength: 3,
    });
    });

    $( ".state-select2" ) .change(function () {
        $("#city_name").val('');
        let param_new = $(this).val();
        var param_state = "?state_id="+param_new;
        $(".city-select2").select2({
        ajax: {
            url: function (param) {
                return "{{route('search.city').'/'}}" + param.term + param_state;
            },
            dataType: 'json',
            delay: 250,
            data: function (param) {
                return {q: param.term, };
            },
            processResults: function (data, param) {
                return {results: data};
            },
            cache: true
        },
        // minimumInputLength: 3,
    });
    });
});
  </script>
  @endsection